version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    tty: true
    stdin_open: true
    ports:
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./log:/ver/log/nginx
    # restart: always
